# Generated by Django 5.2.5 on 2025-10-31 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Porteiro',
            fields=[
                ('matricula', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Setor')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Autorizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Autorizador')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizadores', to='portaria.setor', verbose_name='Setor Principal')),
            ],
            options={
                'verbose_name': 'Autorizador',
                'verbose_name_plural': 'Autorizadores',
                'ordering': ['setor__nome', 'nome'],
                'unique_together': {('nome', 'setor')},
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=194, verbose_name='Nome Completo')),
                ('documento', models.CharField(max_length=20, verbose_name='RG ou CPF')),
                ('motivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo da Visita')),
                ('num_cracha', models.CharField(max_length=10, verbose_name='Número do Crachá')),
                ('filial_origem', models.CharField(max_length=50, verbose_name='Filial de Origem')),
                ('data_hora_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora de Entrada')),
                ('data_hora_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Saída')),
                ('autorizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.autorizador', verbose_name='Pessoa que Autorizou')),
                ('porteiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.porteiro', verbose_name='Porteiro Responsável')),
                ('setor_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.setor', verbose_name='Setor de Destino')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'ordering': ['-data_hora_entrada'],
            },
        ),
    ]
