# Generated by Django 5.0.14 on 2025-11-16 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Autorizador')),
            ],
            options={
                'verbose_name': 'Autorizador',
                'verbose_name_plural': 'Autorizadores',
                'ordering': ['setor__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='EmpresaPrestadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('tipo', models.CharField(choices=[('ENERGIA', 'Energia (CEEE/EQUATORIAL)'), ('LIMPEZA', 'Limpeza'), ('SEGURANCA', 'Segurança'), ('MANUTENCAO', 'Manutenção'), ('TI', 'TI/Tecnologia'), ('OUTROS', 'Outros')], default='OUTROS', max_length=50, verbose_name='Tipo de Empresa')),
            ],
            options={
                'verbose_name': 'Empresa Prestadora',
                'verbose_name_plural': 'Empresas Prestadoras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FuncaoFreelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da Função')),
            ],
            options={
                'verbose_name': 'Função (Freelancer)',
                'verbose_name_plural': 'Funções (Freelancer)',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Porteiro',
            fields=[
                ('matricula', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Porteiro',
                'verbose_name_plural': 'Porteiros',
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Setor')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=194, verbose_name='Nome Completo')),
                ('documento', models.CharField(max_length=20, verbose_name='RG ou CPF')),
                ('data_hora_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora de Entrada')),
                ('data_hora_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Saída')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.funcaofreelancer', verbose_name='Função')),
                ('porteiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.porteiro', verbose_name='Porteiro Responsável')),
            ],
            options={
                'verbose_name': 'Freelancer/Diarista',
                'verbose_name_plural': 'Freelancers/Diaristas',
                'ordering': ['-data_hora_entrada'],
            },
        ),
        migrations.CreateModel(
            name='PrestadorServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_particular', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Empresa Particular (se não for Equatorial)')),
                ('nome_responsavel', models.CharField(max_length=194, verbose_name='Nome do Responsável')),
                ('num_cracha_prestador', models.CharField(max_length=10, verbose_name='Número do Crachá/Cartão')),
                ('categoria_servico', models.CharField(choices=[('MANUTENCAO', 'Manutenção'), ('RETIRADA_MATERIAL', 'Retirada de Materiais')], default='MANUTENCAO', max_length=20, verbose_name='Categoria do Serviço')),
                ('tipo_servico', models.CharField(help_text='Ex: Ar Condicionado, Pedreiro, Elétrica, etc.', max_length=200, verbose_name='Descrição do Serviço')),
                ('data_hora_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora de Entrada')),
                ('data_hora_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Saída')),
                ('veiculo_tipo_saida', models.CharField(blank=True, choices=[('CARRO', 'Carro'), ('MOTO', 'Moto'), ('VAN', 'Van'), ('BICICLETA', 'Bicicleta'), ('CAMINHAO', 'Caminhão'), ('NENHUM', 'Sem veículo')], max_length=20, null=True, verbose_name='Tipo de Veículo (Retirada)')),
                ('veiculo_placa_saida', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa do Veículo (Retirada)')),
                ('autorizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.autorizador', verbose_name='Quem Autorizou a Entrada')),
                ('autorizador_saida_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizacoes_saida_material_prestador', to='portaria.autorizador', verbose_name='Quem Autorizou a Retirada de Material')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.empresaprestadora', verbose_name='Empresa Prestadora')),
                ('porteiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.porteiro', verbose_name='Porteiro Responsável')),
                ('setor_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portaria.setor', verbose_name='Setor de Destino')),
                ('setor_saida_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saidas_material_prestador', to='portaria.setor', verbose_name='Setor (Retirada de Material)')),
            ],
            options={
                'verbose_name': 'Prestador de Serviço',
                'verbose_name_plural': 'Prestadores de Serviço',
                'ordering': ['-data_hora_entrada'],
            },
        ),
        migrations.CreateModel(
            name='AcompanhantePrestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=194, verbose_name='Nome do Acompanhante')),
                ('documento', models.CharField(max_length=20, verbose_name='RG ou CPF')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanhantes', to='portaria.prestadorservico', verbose_name='Prestador')),
            ],
            options={
                'verbose_name': 'Acompanhante (Prestador)',
                'verbose_name_plural': 'Acompanhantes (Prestador)',
            },
        ),
        migrations.CreateModel(
            name='SaidaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nf_almox', models.CharField(max_length=50, verbose_name='Nº NF do Almoxarifado')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_hora_saida', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora de Saída')),
                ('autorizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.autorizador', verbose_name='Quem Autorizou a Saída')),
                ('porteiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.porteiro', verbose_name='Porteiro Responsável')),
                ('prestador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portaria.prestadorservico', verbose_name='Prestador (se aplicável)')),
            ],
            options={
                'verbose_name': 'Saída de Material',
                'verbose_name_plural': 'Saídas de Material',
                'ordering': ['-data_hora_saida'],
            },
        ),
        migrations.AddField(
            model_name='autorizador',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizadores', to='portaria.setor', verbose_name='Setor Principal'),
        ),
        migrations.CreateModel(
            name='TipoServicoEnergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Tipo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_servico', to='portaria.empresaprestadora', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Tipo de Serviço (Energia)',
                'verbose_name_plural': 'Tipos de Serviço (Energia)',
                'ordering': ['empresa__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=194, verbose_name='Nome Completo')),
                ('documento', models.CharField(max_length=20, verbose_name='RG ou CPF')),
                ('motivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo da Visita')),
                ('num_cracha', models.CharField(max_length=10, verbose_name='Número do Crachá')),
                ('data_hora_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora de Entrada')),
                ('data_hora_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Saída')),
                ('autorizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.autorizador', verbose_name='Pessoa que Autorizou')),
                ('porteiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.porteiro', verbose_name='Porteiro Responsável')),
                ('setor_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.setor', verbose_name='Setor de Destino')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'ordering': ['-data_hora_entrada'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='autorizador',
            unique_together={('nome', 'setor')},
        ),
    ]
