# Generated by Django 5.2.5 on 2025-11-02 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitante',
            name='filial_origem',
        ),
    ]
