# Generated by Django 5.2.7 on 2025-11-02 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0002_remove_visitante_filial_origem'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaPrestadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Empresa')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('tipo', models.CharField(choices=[('ENERGIA', 'Energia (CEEE/EQUATORIAL)'), ('LIMPEZA', 'Limpeza'), ('SEGURANCA', 'Segurança'), ('MANUTENCAO', 'Manutenção'), ('TI', 'TI/Tecnologia'), ('OUTROS', 'Outros')], default='OUTROS', max_length=50, verbose_name='Tipo de Empresa')),
            ],
            options={
                'verbose_name': 'Empresa Prestadora',
                'verbose_name_plural': 'Empresas Prestadoras',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FuncaoFreelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da Função')),
            ],
            options={
                'verbose_name': 'Função (Freelancer)',
                'verbose_name_plural': 'Funções (Freelancer)',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='porteiro',
            options={'verbose_name': 'Porteiro', 'verbose_name_plural': 'Porteiros'},
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=194, verbose_name='Nome Completo')),
                ('documento', models.CharField(max_length=20, verbose_name='RG ou CPF')),
                ('data_hora_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora de Entrada')),
                ('data_hora_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Saída')),
                ('porteiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.porteiro', verbose_name='Porteiro Responsável')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.funcaofreelancer', verbose_name='Função')),
            ],
            options={
                'verbose_name': 'Freelancer/Diarista',
                'verbose_name_plural': 'Freelancers/Diaristas',
                'ordering': ['-data_hora_entrada'],
            },
        ),
        migrations.CreateModel(
            name='PrestadorServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(max_length=194, verbose_name='Nome do Responsável')),
                ('matricula_responsavel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Matrícula (se CEEE/EQUATORIAL)')),
                ('documento_responsavel', models.CharField(max_length=20, verbose_name='RG/CPF do Responsável')),
                ('acompanhantes', models.TextField(blank=True, null=True, verbose_name='Nomes dos Acompanhantes (um por linha)')),
                ('quem_solicitou', models.CharField(max_length=100, verbose_name='Quem Solicitou o Serviço')),
                ('tipo_servico', models.CharField(max_length=200, verbose_name='Tipo de Serviço Prestado')),
                ('veiculo_tipo', models.CharField(choices=[('CARRO', 'Carro'), ('CAMINHAO', 'Caminhão'), ('MOTO', 'Moto'), ('VAN', 'Van'), ('NENHUM', 'Sem veículo')], default='NENHUM', max_length=20, verbose_name='Tipo de Veículo')),
                ('veiculo_placa', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa do Veículo')),
                ('veiculo_motorista', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Motorista')),
                ('data_hora_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora de Entrada')),
                ('data_hora_saida', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Saída')),
                ('retira_material', models.BooleanField(default=False, verbose_name='Retira Material?')),
                ('veiculo_saida_nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Veículo de Saída (Nome)')),
                ('veiculo_saida_modelo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Veículo de Saída (Modelo)')),
                ('veiculo_saida_placa', models.CharField(blank=True, max_length=10, null=True, verbose_name='Veículo de Saída (Placa)')),
                ('numero_nf_autorizacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº NF ou Autorização')),
                ('autorizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.autorizador', verbose_name='Quem Autorizou')),
                ('autorizador_saida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizacoes_saida_prestador', to='portaria.autorizador', verbose_name='Quem Autorizou a Saída')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.empresaprestadora', verbose_name='Empresa Prestadora')),
                ('porteiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.porteiro', verbose_name='Porteiro Responsável')),
            ],
            options={
                'verbose_name': 'Prestador de Serviço',
                'verbose_name_plural': 'Prestadores de Serviço',
                'ordering': ['-data_hora_entrada'],
            },
        ),
        migrations.CreateModel(
            name='SaidaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nf_almox', models.CharField(max_length=50, verbose_name='Nº NF do Almoxarifado')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_hora_saida', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora de Saída')),
                ('autorizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.autorizador', verbose_name='Quem Autorizou a Saída')),
                ('porteiro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portaria.porteiro', verbose_name='Porteiro Responsável')),
                ('prestador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portaria.prestadorservico', verbose_name='Prestador (se aplicável)')),
            ],
            options={
                'verbose_name': 'Saída de Material',
                'verbose_name_plural': 'Saídas de Material',
                'ordering': ['-data_hora_saida'],
            },
        ),
        migrations.CreateModel(
            name='TipoServicoEnergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Tipo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos_servico', to='portaria.empresaprestadora', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Tipo de Serviço (Energia)',
                'verbose_name_plural': 'Tipos de Serviço (Energia)',
                'ordering': ['empresa__nome', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='prestadorservico',
            name='tipo_servico_energia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portaria.tiposervicoenergia', verbose_name='Tipo de Serviço (CEEE/EQUATORIAL)'),
        ),
    ]
